### ISSUE TITLE
I meet a error when I run PolicyGradient(PG)/CSDN上的PG.py and PolicyGradient(PG)/PGTorch/main.py

### ISSUE THREAD

**Issue by hischen** [Phoenix-Shen/ReinforcementLearning#1]
NameError: name 'glPushMatrix' is not defined

coule you pls kindy hele me solve it

**Comment by Phoenix-Shen** [comment]
From experience it's because of a library version issue, this doesn't look like a bug in my code, I checked online and it seems to be caused by this issue, please check [this link](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)

从经验上来说是因为某个库的版本问题，这个不像是我的代码中的bug，我在网上查了下，似乎是因为这个问题导致的，请查看[这个链接](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)

**Comment by Phoenix-Shen** [comment]
@hischen 问题解决了么


> From experience it's because of a library version issue, this doesn't look like a bug in my code, I checked online and it seems to be caused by this issue, please check [this link](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)
> 
> 从经验上来说是因为某个库的版本问题，这个不像是我的代码中的bug，我在网上查了下，似乎是因为这个问题导致的，请查看[这个链接](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)

**Comment by Phoenix-Shen** [comment]
> From experience it's because of a library version issue, this doesn't look like a bug in my code, I checked online and it seems to be caused by this issue, please check [this link](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)
> 
> 从经验上来说是因为某个库的版本问题，这个不像是我的代码中的bug，我在网上查了下，似乎是因为这个问题导致的，请查看[这个链接](https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined)

这些报错主要是因为GYM等强化学习库导致的，这些东西的版本要求比较严格，torch的版本要求其实不是很严格，因为我在这个仓库里面只使用到了MLP

**Comment by Phoenix-Shen** [comment]
我最近也遇到了这个问题，直接使用这行命令就解决了
`pip install pyglet==1.5.27`
![error](https://user-images.githubusercontent.com/56379418/210946862-00c6cfee-c92e-4061-b86d-25c77c60f341.png)
